changesetBaseRefs:
  - next
  - origin/next
  - upstream/next

enableScripts: false

logFilters:
  - code: YN0004
    level: discard
  - code: YN0062
    level: discard

nodeLinker: node-modules

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: "@yarnpkg/plugin-version"

preferAggregateCacheInfo: true

preferInteractive: true

yarnPath: .yarn/releases/yarn-3.1.0.cjs
